# Generated by Django 6.1.1 on 2026-10-06 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONFIRM', 'Confirm'), ('REPORT', 'Report')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_verifications', to='spots.hiddenspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('spot', 'user'), name='unique_community_verification_per_user')],
            },
        ),
    ]
